import type { SummaryLevel, TranscriptEntry } from "./context";

export type ReplayFixture = {
  id: string;
  set: "calibration" | "holdout";
  title: string;
  scenario: string;
  repository: string;
  activeGoal: string;
  currentRequest: string;
  currentEntryId: string;
  transcript: TranscriptEntry[];
  mustKeepChunkIds: string[];
  safeToDropChunkIds: string[];
  safetyCriticalChunkIds: string[];
  summaryTargets?: Record<string, SummaryLevel>;
};

export const CURRENT_ENTRY_ID = "user-current";

export const OPEN_CODE_FIXTURE: ReplayFixture = {
  id: "parser-root-cause",
  set: "calibration",
  title: "Parser root cause",
  scenario: "Bugfix with an earlier root-cause finding",
  repository: "acme/ledger-cli",
  activeGoal: "Fix the CSV import without losing repository rules or repeating completed investigation.",
  currentRequest:
    "Fix the quoted-newline CSV parser bug. Preserve the no-dependency rule, keep streaming behavior, and run the existing import checks.",
  currentEntryId: CURRENT_ENTRY_ID,
  transcript: [
    { id: "system-rules", turn: 0, role: "system", content: "Repository rules: do not add runtime dependencies. Never log customer rows. Preserve streaming imports for files larger than memory." },
    { id: "user-original", turn: 1, role: "user", content: "CSV imports split records when a quoted field contains a newline. Diagnose the root cause." },
    { id: "assistant-plan", turn: 2, role: "assistant", content: "I will inspect the parser and every caller before changing code." },
    { id: "call-parser-search", turn: 2, role: "tool_call", toolCallId: "search-parser", content: "rg \"parseRow|split('\\n')\" src test" },
    { id: "result-parser-search", turn: 2, role: "tool_result", toolCallId: "search-parser", content: "src/import/readRows.ts:18 calls parseRow for every line\nsrc/import/parseRow.ts:4 exports parseRow\ntest/import.test.ts:31 tests commas and escaped quotes" },
    { id: "root-cause", turn: 3, role: "decision", dependencies: ["tool:search-parser"], content: "Root cause: readRows splits the byte stream into physical lines before CSV quote state is known. The shared record reader must carry quote state across chunks. It must distinguish doubled quotes from closing quotes, preserve a trailing carriage return until the next byte is known, and emit a logical record only after a newline outside quoted state. parseRow should remain responsible only for fields within an already complete logical record; patching it cannot recover the lost boundary." },
    { id: "call-old-output", turn: 4, role: "tool_call", toolCallId: "old-build", content: "npm run build" },
    { id: "result-old-output", turn: 4, role: "tool_result", toolCallId: "old-build", content: "Build succeeded. This predates the parser change and contains no parser diagnostics. ".repeat(24) },
    { id: "open-work", turn: 5, role: "task_state", pinned: true, dependencies: ["root-cause"], content: "Open work: implement the stateful record boundary, add one quoted-newline regression check, then run import tests and build." },
    { id: "secret-output", turn: 5, role: "assistant", content: "A previous debug capture included API_KEY=sk_fixture_should_never_leave_localhost. Keep this local and do not send it to a selector." },
    { id: CURRENT_ENTRY_ID, turn: 6, role: "user", content: "Fix the quoted-newline CSV parser bug. Preserve the no-dependency rule, keep streaming behavior, and run the existing import checks." },
  ],
  mustKeepChunkIds: ["system-rules", "user-original", "tool:search-parser", "root-cause", "open-work", "secret-output", CURRENT_ENTRY_ID],
  safeToDropChunkIds: ["assistant-plan", "tool:old-build"],
  safetyCriticalChunkIds: ["system-rules", "secret-output"],
  summaryTargets: { "root-cause": "long", "tool:old-build": "drop" },
};

export const REPLAY_FIXTURES: ReplayFixture[] = [
  OPEN_CODE_FIXTURE,
  {
    id: "refactor-constraints",
    set: "calibration",
    title: "Refactor constraints",
    scenario: "Refactor with binding repository constraints",
    repository: "acme/web",
    activeGoal: "Move validation into the shared request path without changing public behavior.",
    currentRequest: "Finish the validation refactor and preserve the public error codes and zero-dependency rule.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "developer", content: "Do not add dependencies. Public error codes E_INPUT and E_AUTH are API contracts." },
      { id: "original", turn: 1, role: "user", content: "The three route handlers duplicate request validation. Centralize the existing checks." },
      { id: "call-shared", turn: 2, role: "tool_call", toolCallId: "shared", content: "rg \"E_INPUT|E_AUTH\" src" },
      { id: "result-shared", turn: 2, role: "tool_result", toolCallId: "shared", content: "All three handlers first parse JSON, return E_INPUT for malformed bodies or missing required fields, and return E_AUTH for rejected credentials. src/http/validate.ts already exposes validateRequest with the same parsing and credential checks, but callers must preserve each handler's existing status code and public error payload. The shared helper throws typed failures and has no runtime dependencies." },
      { id: "decision", turn: 3, role: "decision", dependencies: ["tool:shared"], content: "Reuse validateRequest in src/http/validate.ts and keep each handler's existing error mapping." },
      { id: "call-css", turn: 3, role: "tool_call", toolCallId: "css", content: "npm run build" },
      { id: "result-css", turn: 3, role: "tool_result", toolCallId: "css", content: "Unrelated CSS optimization output. ".repeat(35) },
      { id: "current", turn: 6, role: "user", content: "Finish the validation refactor and preserve the public error codes and zero-dependency rule." },
    ],
    mustKeepChunkIds: ["rules", "original", "tool:shared", "decision", "current"],
    safeToDropChunkIds: ["tool:css"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:shared": "long", "tool:css": "drop" },
  },
  {
    id: "task-switch",
    set: "holdout",
    title: "Task switch",
    scenario: "A new task replaces an unrelated completed task",
    repository: "acme/dashboard",
    activeGoal: "Fix keyboard focus in the settings dialog.",
    currentRequest: "Make the settings dialog return focus to its trigger when it closes.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Preserve keyboard accessibility and use existing browser APIs before adding packages." },
      { id: "old-user", turn: 1, role: "user", content: "Optimize the invoice export query." },
      { id: "old-call", turn: 2, role: "tool_call", toolCallId: "invoice", content: "EXPLAIN ANALYZE invoice query" },
      { id: "old-result", turn: 2, role: "tool_result", toolCallId: "invoice", content: "Invoice query plan and index statistics. ".repeat(35) },
      { id: "old-summary", turn: 3, role: "assistant", content: "Invoice export optimization is complete and verified." },
      { id: "current", turn: 6, role: "user", content: "Make the settings dialog return focus to its trigger when it closes." },
    ],
    mustKeepChunkIds: ["rules", "current"],
    safeToDropChunkIds: ["old-user", "tool:invoice", "old-summary"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:invoice": "drop" },
  },
  {
    id: "large-test-output",
    set: "calibration",
    title: "Large test output",
    scenario: "A large stale test log competes with a current diagnosis",
    repository: "acme/worker",
    activeGoal: "Repair retry accounting without repeating the diagnosis.",
    currentRequest: "Implement the retry counter fix and run the focused worker check.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Retry counters are persisted atomically; never acknowledge a job before persistence succeeds." },
      { id: "call-all-tests", turn: 1, role: "tool_call", toolCallId: "all-tests", content: "npm test" },
      { id: "result-all-tests", turn: 1, role: "tool_result", toolCallId: "all-tests", content: "Passing legacy test details, coverage rows, and module timings. ".repeat(80) },
      { id: "call-retry", turn: 2, role: "tool_call", toolCallId: "retry", content: "rg \"retryCount\" src test" },
      { id: "result-retry", turn: 2, role: "tool_result", toolCallId: "retry", content: "The focused search found retry accounting in worker.ts, persistence in job-store.ts, and the matching expectation in retry.test.ts. The transaction already saves the whole job atomically and acknowledgement happens afterward. The defect is ordering inside worker.ts: it increments retryCount only after save(), while retry.test.ts expects the incremented value to be included in that atomic save." },
      { id: "root-cause", turn: 3, role: "decision", dependencies: ["tool:retry"], content: "Increment retryCount before the atomic save; the current order persists the previous value." },
      { id: "current", turn: 6, role: "user", content: "Implement the retry counter fix and run the focused worker check." },
    ],
    mustKeepChunkIds: ["rules", "tool:retry", "root-cause", "current"],
    safeToDropChunkIds: ["tool:all-tests"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:all-tests": "drop", "tool:retry": "short" },
  },
  {
    id: "repeated-inspection",
    set: "calibration",
    title: "Repeated inspection",
    scenario: "Identical file reads are deduplicated deterministically",
    repository: "acme/config",
    activeGoal: "Change the timeout at its single source of truth.",
    currentRequest: "Raise the request timeout to 30 seconds and run the config check.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Configuration remains in src/config.ts; do not introduce environment-specific defaults." },
      { id: "call-read-1", turn: 1, role: "tool_call", toolCallId: "read-1", content: "Get-Content src/config.ts" },
      { id: "result-read-1", turn: 1, role: "tool_result", toolCallId: "read-1", content: "export const requestTimeoutMs = 15000;\nexport const retries = 2;" },
      { id: "call-read-2", turn: 2, role: "tool_call", toolCallId: "read-2", content: "Get-Content src/config.ts" },
      { id: "result-read-2", turn: 2, role: "tool_result", toolCallId: "read-2", content: "export const requestTimeoutMs = 15000;\nexport const retries = 2;" },
      { id: "decision", turn: 3, role: "decision", dependencies: ["tool:read-2"], content: "Edit requestTimeoutMs only; every caller imports this constant." },
      { id: "current", turn: 6, role: "user", content: "Raise the request timeout to 30 seconds and run the config check." },
    ],
    mustKeepChunkIds: ["rules", "tool:read-2", "decision", "current"],
    safeToDropChunkIds: ["tool:read-1"],
    safetyCriticalChunkIds: ["rules"],
  },
  {
    id: "failed-tool-fixed",
    set: "calibration",
    title: "Failed tool then fix",
    scenario: "A failed command and the later corrective result remain explainable",
    repository: "acme/api",
    activeGoal: "Finish the migration after correcting the command path.",
    currentRequest: "Apply the verified migration edit and rerun the focused check.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Never modify production migration history; only edit the new unshipped migration." },
      { id: "call-failed", turn: 1, role: "tool_call", toolCallId: "failed", content: "npm test migrations/wrong-path.test.ts" },
      { id: "result-failed", turn: 1, role: "tool_result", toolCallId: "failed", error: true, content: "No test files found. The requested path does not exist." },
      { id: "call-fixed", turn: 2, role: "tool_call", toolCallId: "fixed", content: "npm test test/migrations/new-user.test.ts" },
      { id: "result-fixed", turn: 2, role: "tool_result", toolCallId: "fixed", content: "Focused migration test reproduced the missing unique index in the new unshipped migration 20260922_add_user_alias.sql. The required contract is exact: add UNIQUE INDEX users_tenant_alias_uq ON users (tenant_id, lower(alias)) WHERE deleted_at IS NULL; keep the existing non-unique users_alias_lookup index because read queries depend on it; do not edit migrations with lower sequence numbers. The duplicate fixture must still fail with SQLSTATE 23505." },
      { id: "decision", turn: 3, role: "decision", dependencies: ["tool:fixed"], content: "Add the unique index to the new unshipped migration; do not touch historical files." },
      { id: "call-noise", turn: 3, role: "tool_call", toolCallId: "noise", content: "npm run lint" },
      { id: "result-noise", turn: 3, role: "tool_result", toolCallId: "noise", content: "Unrelated lint formatter details. ".repeat(35) },
      { id: "current", turn: 6, role: "user", content: "Apply the verified migration edit and rerun the focused check." },
    ],
    mustKeepChunkIds: ["rules", "tool:failed", "tool:fixed", "decision", "current"],
    safeToDropChunkIds: ["tool:noise"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:fixed": "full", "tool:noise": "drop" },
  },
  {
    id: "old-security-rule",
    set: "holdout",
    title: "Old security rule",
    scenario: "A safety instruction survives many unrelated turns",
    repository: "acme/audit",
    activeGoal: "Add the audit export without exposing credentials.",
    currentRequest: "Implement the JSON export using the existing redaction helper.",
    currentEntryId: "current",
    transcript: [
      { id: "security", turn: 0, role: "developer", content: "Audit exports must redact tokens, cookies, Authorization headers, and private keys before writing any file." },
      { id: "old-call", turn: 1, role: "tool_call", toolCallId: "old", content: "npm run build" },
      { id: "old-result", turn: 1, role: "tool_result", toolCallId: "old", content: "Historical bundle sizes and source-map entries. ".repeat(50) },
      { id: "helper", turn: 3, role: "decision", content: "Reuse redactSecrets from src/security/redact.ts for every exported record." },
      { id: "current", turn: 6, role: "user", content: "Implement the JSON export using the existing redaction helper." },
    ],
    mustKeepChunkIds: ["security", "helper", "current"],
    safeToDropChunkIds: ["tool:old"],
    safetyCriticalChunkIds: ["security"],
    summaryTargets: { "tool:old": "drop" },
  },
  {
    id: "user-correction",
    set: "holdout",
    title: "User correction",
    scenario: "A later correction replaces an earlier requirement",
    repository: "acme/reporting",
    activeGoal: "Export reports in the corrected format.",
    currentRequest: "Finish the CSV-only report export with semicolon delimiters.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Do not add a spreadsheet dependency; use the standard CSV writer." },
      { id: "old-request", turn: 1, role: "user", content: "Export both XLSX and CSV using comma delimiters." },
      { id: "old-plan", turn: 2, role: "assistant", content: "I will add two export formats and default CSV to commas." },
      { id: "correction", turn: 3, role: "user", content: "Correction: CSV only, with semicolon delimiters. Do not build XLSX support." },
      { id: "old-output", turn: 3, role: "tool_call", toolCallId: "old-output", content: "npm run build" },
      { id: "old-output-result", turn: 3, role: "tool_result", toolCallId: "old-output", content: "Unrelated static asset report. ".repeat(40) },
      { id: "current", turn: 6, role: "user", content: "Finish the CSV-only report export with semicolon delimiters." },
    ],
    mustKeepChunkIds: ["rules", "correction", "current"],
    safeToDropChunkIds: ["old-request", "old-plan", "tool:old-output"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:old-output": "drop" },
  },
  {
    id: "subagent-result",
    set: "holdout",
    title: "Subagent result",
    scenario: "A delegated investigation result supports the current decision",
    repository: "acme/search",
    activeGoal: "Fix ranking at the shared normalization boundary.",
    currentRequest: "Implement the normalization fix identified by the subagent and run ranking tests.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Ranking changes must preserve stable ordering for equal scores." },
      { id: "call-subagent", turn: 1, role: "tool_call", toolCallId: "subagent", content: "Delegate ranking root-cause investigation" },
      { id: "result-subagent", turn: 1, role: "tool_result", toolCallId: "subagent", content: "The subagent traced every ranking caller to normalizeScore in src/rank.ts. normalizeScore rounds the raw score to two decimals before multiplying by the query weight, which collapses close candidates prematurely. Move rounding after weighting, retain the existing stable-sort tie breaker based on original input position, and run rank-unit.test.ts plus search-order.test.ts. No caller-specific patches are needed." },
      { id: "call-other", turn: 2, role: "tool_call", toolCallId: "other", content: "Delegate documentation spellcheck" },
      { id: "result-other", turn: 2, role: "tool_result", toolCallId: "other", content: "Unrelated documentation spelling suggestions. ".repeat(45) },
      { id: "decision", turn: 3, role: "decision", dependencies: ["tool:subagent"], content: "Move rounding after weighting in normalizeScore and keep the existing stable-sort tie breaker." },
      { id: "current", turn: 6, role: "user", content: "Implement the normalization fix identified by the subagent and run ranking tests." },
    ],
    mustKeepChunkIds: ["rules", "tool:subagent", "decision", "current"],
    safeToDropChunkIds: ["tool:other"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:subagent": "long", "tool:other": "drop" },
  },
  {
    id: "session-resume",
    set: "calibration",
    title: "Session resume",
    scenario: "A resumed session keeps open work and drops stale build chatter",
    repository: "acme/cache",
    activeGoal: "Resume the unfinished cache invalidation fix.",
    currentRequest: "Resume the open invalidation fix from the recorded task state.",
    currentEntryId: "current",
    transcript: [
      { id: "rules", turn: 0, role: "system", content: "Cache invalidation must remain tenant-scoped and fail closed when the tenant id is missing." },
      { id: "old-build-call", turn: 1, role: "tool_call", toolCallId: "old-build", content: "npm run build" },
      { id: "old-build-result", turn: 1, role: "tool_result", toolCallId: "old-build", content: "Build chunk names, module counts, and asset timing rows. ".repeat(55) },
      { id: "old-chat", turn: 2, role: "assistant", content: "The earlier documentation cleanup is complete." },
      { id: "open-work", turn: 4, role: "task_state", pinned: true, content: "Resume state: tenant id is lost in invalidateMany; implementation and focused test are still open. Cache may be cold." },
      { id: "current", turn: 6, role: "user", content: "Resume the open invalidation fix from the recorded task state." },
    ],
    mustKeepChunkIds: ["rules", "open-work", "current"],
    safeToDropChunkIds: ["tool:old-build", "old-chat"],
    safetyCriticalChunkIds: ["rules"],
    summaryTargets: { "tool:old-build": "drop" },
  },
];
